//
// Created by Aadavn Nimalthas on 2026-03-25.
//

#ifndef CLASSICAL_SUPER_RESOLUTION_IMAGE_LOADER_H
#define CLASSICAL_SUPER_RESOLUTION_IMAGE_LOADER_H


class image_loader
{
};


#endif //CLASSICAL_SUPER_RESOLUTION_IMAGE_LOADER_H