//
// Created by Aadavn Nimalthas on 2026-03-25.
//

#ifndef CLASSICAL_SUPER_RESOLUTION_UPSCALE_H
#define CLASSICAL_SUPER_RESOLUTION_UPSCALE_H


class upscale
{
};


#endif //CLASSICAL_SUPER_RESOLUTION_UPSCALE_H