//
// Created by Aadavn Nimalthas on 2026-03-25.
//

#ifndef CLASSICAL_SUPER_RESOLUTION_MATH_UTILS_H
#define CLASSICAL_SUPER_RESOLUTION_MATH_UTILS_H


class math_utils
{
};


#endif //CLASSICAL_SUPER_RESOLUTION_MATH_UTILS_H